version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devvault-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - devvault-network

  api:
    build: ./src/DevVault.Api
    container_name: devvault.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=authdb;Username=auth;Password=auth
    depends_on:
      - postgres
      - redis
    networks:
      - devvault-network

networks:
  devvault-network:
    driver: bridge

volumes:
  pgdata:
